# GET all words
GET http://localhost:3000/api/words/tags

###

# POST a new word

post http://localhost:3000/api/words/
Content-Type: application/json

{ "foreign_word": "dog", "finnish_word": "koira", "language": 1, "tag": 1}

###

# POST a new language

post http://localhost:3000/api/words/tags/
Content-Type: application/json

{ "tag": "vehicles"}

###

# DELETE a word by ID
DELETE http://localhost:3000/api/words/1

###

# PATCH to partially update a word by ID

PATCH http://localhost:3000/api/words/1
Content-Type: application/json

{
  "finnish_word": "hiiri"
}

###

# FILTER to get specific data

GET http://localhost:3000/api/words?language=1&tag=1